### ISSUE TITLE
Project points onto unit sphere

### ISSUE THREAD

**Issue by jonthesquirrel** [geodesicraft/geodesicraft.github.io#131]
Or elliptical sphere. Can also project onto specific radius at this point to avoid scaling later as well. This will make it not matter if the Cartesian-constructed points are not the radius of a unit sphere in the first place.

**Comment by jonthesquirrel** [comment]
Camera scaling will be needed #132

**Comment by comfysquirrel** [comment]
Made obsolete by #143
