### ISSUE TITLE
Use the Delaunay Triangulation to subdivide any 3D shape

### ISSUE THREAD

**Issue by jonthesquirrel** [geodesicraft/geodesicraft.github.io#138]
Solves #130 and #129.

This would also allow for additional customization, such as clicking in the shape or adding a point with a GUI prompt, and then integrating that point into the overall geodesic composition.

With this method, additional options for import/export of shape and generating settings data would need to be added, because the old method of copying a single command to save the state would not exist.

**Comment by comfysquirrel** [comment]
Made obsolete by #143
